### ISSUE TITLE
Time is always the same on every map.

### ISSUE THREAD

**Issue by ertup0** [Nak2/StormFox2#12]
I remember before some updates, time was random on every map, but now on every map, time is 3:45.
In sf2 settings default time is -1, and no errors in the console.
I reinstalled gmod and addon few times, but the issue still persists.

**Comment by Nak2** [comment]
I'll look into it, but you should see a message in the console saying: `[StormFox2] Saving time | <Time>` when GM:ShutDown gets called ( When game or server is about to close ), this number is used if sf_real_time and sf_start_time is both -1.

I'll make a detailed launch message appear in the next version and do some checks.

**Comment by ertup0** [comment]
I don't know what you did, but one of the updates fixed my problem. Thank you!

**Comment by Nak2** [comment]
I did find a bug a few days ago that overwrote settings, if they got called before SF knew about them.
Happy to hear it got solved.
