### ISSUE TITLE
error when loading TF2 map cp_5gorge

### ISSUE THREAD

**Issue by EntranceJew** [Nak2/StormFox2#20]
```
[StormFox 2] lua/stormfox2/framework/cl_envioment.lua:921: lua/stormfox2/framework/cl_envioment.lua:667: bad argument #1 to 'ipairs' (table expected, got no value)
    1. cor_scan - [C]:-1
        2. unknown - lua/stormfox2/framework/cl_envioment.lua:921
```
sometimes `surf` can be `nil`, i'm not sure what the correct behavior is in this circumstance so i can't adequately submit a PR for it

https://github.com/Nak2/StormFox2/blob/3a25356b60fdb7748d80604e4da531f14ae54fd2/lua/stormfox2/framework/cl_envioment.lua#L667

**Comment by Nak2** [comment]
Patched in hotfix.
Surfaces are a bit buggy in many cases. Willox said that he couldn't locate the problems I gave him, after he added the function.

Sadly unsolvable for now, but added a safeguard against it causing errors.
