### ISSUE TITLE
Bug: filter to darken maps still comes up when SF is disabled

### ISSUE THREAD

**Issue by Scott-McKool** [Nak2/StormFox2#21]
Even though i have SF disabled, the darkness filter will still come on every once and awhile.
In the server options, I have SF disabled
In client options, under effects I have "Extra Darkness" disabled 
this is what the server options show
![image](https://user-images.githubusercontent.com/44004555/131201974-43948c7b-8c13-4e34-a219-dde03b59d285.png)
I can temporarily get the brightness back to normal by enabling and disabling SF in the server options, which puts this in console:
![image](https://user-images.githubusercontent.com/44004555/131202032-8e16db5d-188a-4073-8977-d2f882404312.png)

**Comment by Nak2** [comment]
Darn, forgot to add a check. Adding it now.

**Comment by Nak2** [comment]
Should be fixed now. I've also fixed the "breath" effect showing up when disabled.
