### ISSUE TITLE
Major issue with emitters

### ISSUE THREAD

**Issue by jellyton69** [Nak2/StormFox2#27]
I've been debugging a major crash lag issue I've been experiencing for a few weeks now, and I've come to the conclusion that StormFox is to blame. 

The issue in question is: **CUtlLinkedList overflow! (exhausted memory allocator)**. I've done exhaustive testing with and without StormFox, and the issue only occurs when SF is on the server.

I believe the issue is that you never run the Finish() function on your particle emitters. Because of this, your particle emitters are never released from memory. This is why this issue only happens after a player has been on the server for a while.

**Comment by Nak2** [comment]
I currently only got two particle-emiters in SF2. Both used globally for weather.
I can add a timer to destroy the emitter, and remake another. But unsure if it would help,

I'll look around and see what I can do.

**Comment by jellyton69** [comment]
I think the timer would help immensely, I don't recall the name of the lightmode, but its the one that allows for smooth transitioning no lag that requires me to bake the light_env into the map at compile by giving it a name.

**Comment by Nak2** [comment]
I'll make a 10 min timer, where it will destroy the particleemitter and recreate a new one when being called. Hopefully this will fix it.

**Comment by Nak2** [comment]
If it is the emitters that cause problems, they should be cleared every second minute now.
https://github.com/Nak2/StormFox2/commit/e568916acf25bbcab1eeed2ea7eb7326e71d5e2f

**Comment by Nak2** [comment]
Ups, wrong button. Closing it now since it seems resolved.
