### ISSUE TITLE
Footstep sound will not be replaced when moving with jumps

### ISSUE THREAD

**Issue by klen-list** [Nak2/StormFox2#28]
I think it's problems with `noSpam` check. When you moving and jump at the same time, you emit multiple sounds which are ignored by `GetFootstep` in `StormFox2.footstep.detecter` and we can hear original footstep sound. I get fixed this when copy `noSpam` check into `StormFox2.lastfootprint`, but idk how correct it is.

**Comment by klen-list** [comment]
Yes, this it's `noSpam' check. When I removed it, the bug was fixed

**Comment by Nak2** [comment]
Thanks for the heads-up. Removed the check.
