### ISSUE TITLE
[Crash] It crashes the game when cleanup the map

### ISSUE THREAD

**Issue by exe1566** [Nak2/StormFox2#36]
/proc/1/fd/4(+0x2f4e9)[0xf794d4e9]
linux-gate.so.1(__kernel_rt_sigreturn+0x0)[0xf7ef7570]
/home/container/garrysmod/bin/server_srv.so(+0xd8c9a8)[0xf24f79a8]
/home/container/garrysmod/bin/server_srv.so(+0xd8cd02)[0xf24f7d02]
/home/container/garrysmod/bin/server_srv.so(+0xd8cdf8)[0xf24f7df8]
/home/container/garrysmod/bin/server_srv.so(+0xdfd548)[0xf2568548]
/home/container/garrysmod/bin/server_srv.so(+0xdfd748)[0xf2568748]
/home/container/garrysmod/bin/server_srv.so(+0xdfe257)[0xf2569257]
/home/container/garrysmod/bin/server_srv.so(+0xe994c7)[0xf26044c7]
/home/container/garrysmod/bin/server_srv.so(+0xce445e)[0xf244f45e]
/home/container/garrysmod/bin/server_srv.so(+0xce55bb)[0xf24505bb]
/home/container/garrysmod/bin/server_srv.so(+0x59cf6f)[0xf1d07f6f]
/home/container/garrysmod/bin/server_srv.so(+0x6ce318)[0xf1e39318]
/home/container/garrysmod/bin/lua_shared_srv.so(+0x5c9b9)[0xedb499b9]
/home/container/garrysmod/bin/lua_shared_srv.so(lua_pcall+0x48)[0xedb3ce38]
/home/container/garrysmod/bin/lua_shared_srv.so(+0x197dc)[0xedb067dc]
/home/container/garrysmod/bin/lua_shared_srv.so(+0x230c6)[0xedb100c6]
/home/container/garrysmod/bin/lua_shared_srv.so(+0x236cb)[0xedb106cb]
/home/container/garrysmod/bin/lua_shared_srv.so(+0x18e79)[0xedb05e79]
/home/container/garrysmod/bin/server_srv.so(+0x6b8d42)[0xf1e23d42]
/home/container/bin/engine_srv.so(+0xe649b)[0xf5a3d49b]
/home/container/bin/engine_srv.so(+0xe68cc)[0xf5a3d8cc]
/home/container/bin/engine_srv.so(+0x13c320)[0xf5a93320]
/home/container/bin/engine_srv.so(+0x149648)[0xf5aa0648]
/home/container/bin/engine_srv.so(+0x149926)[0xf5aa0926]
/home/container/bin/engine_srv.so(+0x14996d)[0xf5aa096d]
/home/container/bin/engine_srv.so(+0x1da3f9)[0xf5b313f9]
/home/container/bin/engine_srv.so(+0x1d7cc6)[0xf5b2ecc6]
bin/dedicated_srv.so(+0x973ba)[0xf6f223ba]
/home/container/bin/engine_srv.so(+0x1d7d6d)[0xf5b2ed6d]
/home/container/bin/engine_srv.so(+0x22e818)[0xf5b85818]
/home/container/bin/engine_srv.so(+0x1d807d)[0xf5b2f07d]
bin/dedicated_srv.so(+0x97078)[0xf6f22078]
bin/dedicated_srv.so(+0xf6098)[0xf6f81098]
bin/dedicated_srv.so(+0xf6098)[0xf6f81098]
bin/dedicated_srv.so(+0x418fa)[0xf6ecc8fa]
./srcds_linux[0x8048aab]
/lib/i386-linux-gnu/libc.so.6(__libc_start_main+0x106)[0xf7c9ce46]
./srcds_linux[0x8048c33]

Lua Stack:
[C][+0] [C] in STORMFOX_CLEANUPMAP
[L][+1] lua/autorun/stormfox2.lua:223 in field CleanUpMap Line 213 -> 224
[m][+2] lua_run:1 in anonymous function Line 0 -> 1

 End of stack trace
 
Here is the log.

**Comment by Nak2** [comment]
Ensure to keep StormFox up to date.
Hotfix was pushed last week: https://github.com/Nak2/StormFox2/commit/41822c2d262769a128a8400842252ec5a188b220
Also pushed to Steam
