### ISSUE TITLE
A Small but noticeable cosmetic issue I came across

### ISSUE THREAD

**Issue by cerool** [Nak2/StormFox2#7]
The rain fog particles seem to be a bit off since sometimes when they lift or stop and stay still a pretty abrupt sharp edge leading to a sudden nothing at the bottom, not sure what is causing this as It mostly happens when I'm walking and standing still, though it sometimes gets a bit crazy when running, I also have tested it on some other maps and discovered the issue isn't linked to a single map, though at the moment I only have 2 different maps screenshotted with it occurring. 

I am very sorry if this is the incorrect place to put this. Thank you.

And here are some pictures as an example.
![20210409124656_1](https://user-images.githubusercontent.com/29087251/114241050-2ad47e80-994e-11eb-868b-18dea5372839.jpg)
![20210409124544_2](https://user-images.githubusercontent.com/29087251/114241194-65d6b200-994e-11eb-8150-3fcadc1ca3e5.jpg)
![20210406131322_1](https://user-images.githubusercontent.com/29087251/114241885-8e12e080-994f-11eb-9848-cb9f9a189271.jpg)

**Comment by Nak2** [comment]
I did try and make it stop above the ground a bit, depending on the wind-angle.
This is to stop the effect going through roofs.

Altho I could disable this when the player is outside, I'll do a few tests.

**Comment by Xeddius** [comment]
I've also noticed this effect, when snowing it is quite noticeable where the textures cut-off.
I really like this addon as a successor to the "Simpleweather" script I've been using for so long. The ability to prevent the rain from passing through glass has motivated me to switch, however some small things I'd love to see improved is custom texture blacklist to keep rain from passing through things that it shouldn't for maps with custom/weird texture setups, thunderstorms, and rain adjustment (I find at night it's too dark for the rain to be seen even in the lighted back-alley of my map, even with extra darkness disabled.) The simpleweather rain was just the right level of brightness for me, but the fact that it was passing through my ceilings has made it no longer viable. I look forward to seeing this awesome addon improve in the future and I will donate once I have some extra funds.

**Comment by Nak2** [comment]
Should be fixed in 2.08 I just pushed today:
- Texture cutoff
- Fixed large snow-sprites being too visible.
Among others things

I'll look into the other features like droplets on screen for the next update.
